version: '3'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: szymonkruk321
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend

  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: szymonkruk321
      DB_DATABASE: postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
