version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: szymonkruk321
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  api:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
